name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: metadata
        uses: 100terres/job-setup@0d2a4b85eeac0d959c2769f0c100db75c9cf94e2
        with:
          output-changed-files: "true"
          changed-files-filters: |
            **/*.json
            **/*.md
            **/*.yml

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Install NodeJS
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install NodeJS Dependencies
        run: pnpm install

      - name: Check Format
        run: pnpm run format:check -- ${{ steps.metadata.outputs.changed-files }}
