name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: metadata
        uses: 100terres/job-setup@1a138021f1ca978c21f49dbabc873c66e21a3c30
        with:
          output-changed-files: "true"

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Install NodeJS
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install NodeJS Dependencies
        run: pnpm install

      - name: Check Format
        run: pnpm run format:check -- ${{ steps.metadata.outputs.changed-files }}
